$(document).ready(function(){
  $(".toggleMobNav").click(function(){
    $(".toggleSection").slideToggle();
  })
  navigation 
  $(".toggleMobNav").click(function(){
    $(".toggleSection").slideToggle();
    $(".toggleMobNav").toggleClass('fixed');
  })
});
